---
#- name: Installing curl packages using apt
#  become: true
#  apt:
#    pkg: "curl"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'Ubuntu'

#- name: Installing curl packages using yum
#  become: true
#  yum:
#    pkg: "curl"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#- name: Installing curl packages using pacman
#  pacman:
#    name: "curl"
#    state: present
#  when: ansible_distribution == 'MacOSX'

- name: Installing curl packages
  become: true
  package:
    name: "curl"
    state: present
